# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDSwipeViewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  # Pods for DDSwipeViewDemo

  target 'DDSwipeViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDSwipeViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
